[project]
name = "simple-evals"
version = "0.1.0"
packages = ["simple_evals"] 
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "pandas>=2.3.1",
    "tabulate>=0.9.0",
    "vllm>=0.10.0",
]
